import { useEffect, useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectGroup, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group";
import { ConfirmDialog } from "../components/ConfirmDialog.jsx";
import { EmptyState, Panel, StatusPill, Table } from "../components/ui.jsx";
import { money } from "../lib/app-helpers.js";
import { filterTransactions } from "../lib/presentation.js";

function FilterSelect({ label, value, options, onChange }) { const plural = label === "Category" ? "categories" : `${label.toLowerCase()}s`; return <Select value={value || "all"} onValueChange={(next) => onChange(next === "all" ? "" : next)}><SelectTrigger aria-label={label}><SelectValue /></SelectTrigger><SelectContent><SelectGroup><SelectItem value="all">All {plural}</SelectItem>{options.map((option) => <SelectItem key={option} value={option}>{option}</SelectItem>)}</SelectGroup></SelectContent></Select>; }
export function TransactionsView({ state, intent, onAddTransaction, onEditTransaction, onDeleteTransaction }) {
  const [query, setQuery] = useState(""); const [category, setCategory] = useState(""); const [account, setAccount] = useState(""); const [scope, setScope] = useState("month"); const [deleteItem, setDeleteItem] = useState(null);
  useEffect(() => { if (intent?.allMonths) { setScope("all"); setQuery(""); setCategory(""); setAccount(""); } if (intent?.transactionId) requestAnimationFrame(() => document.getElementById(`transaction-${intent.transactionId}`)?.focus()); }, [intent]);
  const rows = useMemo(() => filterTransactions(state.transactions, { month: state.selectedMonth, allMonths: scope === "all", query, category, account }), [state.transactions, state.selectedMonth, scope, query, category, account]);
  const anyFilters = Boolean(query || category || account);
  return <section aria-labelledby="transactions-heading"><div className="view-heading"><div><h2 id="transactions-heading" tabIndex="-1">Transaction ledger</h2><p>Review saved entries. Editing sends one update when you save.</p></div><Button onClick={onAddTransaction}>Add transaction</Button></div>{intent?.savedOutsideMonth && <p className="notice success">Saved outside the selected month. All months is shown so you can review it.</p>}<Panel><div className="ledger-toolbar"><Input aria-label="Search transactions" placeholder="Search merchant, description, or notes" value={query} onChange={(event) => setQuery(event.target.value)} /><FilterSelect label="Category" value={category} options={state.categories.map((item) => item.name)} onChange={setCategory} /><FilterSelect label="Account" value={account} options={state.accounts.map((item) => item.name)} onChange={setAccount} /><ToggleGroup type="single" value={scope} onValueChange={(value) => value && setScope(value)} aria-label="Transaction month scope"><ToggleGroupItem value="month">Selected month</ToggleGroupItem><ToggleGroupItem value="all">All months</ToggleGroupItem></ToggleGroup></div>
    {!rows.length ? <EmptyState title={anyFilters ? "No matching transactions" : scope === "month" ? "No transactions this month" : "No transactions yet"} message={anyFilters ? "Clear the filters to see more entries." : "Add a transaction to start your ledger."} action={anyFilters ? <Button variant="outline" onClick={() => { setQuery(""); setCategory(""); setAccount(""); }}>Clear filters</Button> : <Button onClick={onAddTransaction}>Add transaction</Button>} /> : <><div className="ledger-desktop"><Table label="Transactions" headers={["Date", "Merchant", "Category", "Account", "Amount", ""]}>{rows.map((item) => <tr id={`transaction-${item.id}`} tabIndex="-1" className={intent?.transactionId === item.id ? "is-highlighted" : ""} key={item.id}><td>{item.date || "Invalid date"}</td><td><strong className="table-primary">{item.merchantPayee || item.description || "Untitled transaction"}</strong>{item.merchantPayee && item.description ? <span className="table-secondary">{item.description}</span> : null}</td><td><strong className="table-primary">{item.category}</strong><span className="table-secondary">{item.subcategory}</span></td><td>{item.account}</td><td className="money"><StatusPill tone={item.type === "Income" ? "success" : "neutral"}>{item.type}</StatusPill> {money(item.amount, state.currency)}</td><td><div className="row-actions"><Button id={`edit-${item.id}`} variant="outline" size="sm" onClick={() => onEditTransaction(item)}>Edit</Button><Button variant="ghost" size="sm" onClick={() => setDeleteItem(item)}>Delete</Button></div></td></tr>)}</Table></div><div className="ledger-mobile">{rows.map((item) => <article id={`transaction-${item.id}`} tabIndex="-1" key={item.id}><div><strong>{item.merchantPayee || item.description || "Untitled transaction"}</strong><span>{item.date} · {item.category} / {item.subcategory}</span><span>{item.account}</span></div><div><strong>{money(item.amount, state.currency)}</strong><span>{item.type}</span></div><Button id={`edit-${item.id}`} variant="outline" size="sm" onClick={() => onEditTransaction(item)}>Edit</Button></article>)}</div></>}
  </Panel><ConfirmDialog open={Boolean(deleteItem)} title="Delete transaction?" description={`${deleteItem?.merchantPayee || deleteItem?.description || "This transaction"} will be permanently removed.`} destructive confirmLabel="Delete transaction" onCancel={() => setDeleteItem(null)} onConfirm={async () => { await onDeleteTransaction(deleteItem.id); setDeleteItem(null); }} /></section>;
}
